spring:
  cloud:
    gateway:
      routes:
        - id : beer-service
          uri: lb://beer-service
          predicates:
            - Path=/api/v1/beer/*,/api/v1/beer*,/api/v1/beer/beerUpc/*
        - id: beer-order-service
          uri: lb://beer-order-service
          predicates:
            - Path=/api/v1/customers**,/api/v1/customers/**
        - id: beer-inventory-service
          uri: lb://beer-inventory-service
          predicates:
            - Path=/api/v1/beer/*/inventory
        - id: inventory-failover
          uri: lb://inventory-failover
          predicates:
            - Path=/inventory-failover

